/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ANGULARRT
#define ANGULARRT

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class AngularRT : public RooAbsPdf {
public:
  AngularRT() {} ; 
  AngularRT(const char *name, const char *title,
	      RooAbsReal& _ctK,
	      RooAbsReal& _ctL,
	      RooAbsReal& _phi,
	      RooAbsReal& _FsS,
	      RooAbsReal& _AsS,
	      RooAbsReal& _As5S,
	      RooAbsReal& _FlS,
	      RooAbsReal& _P1S,
	      RooAbsReal& _P5pS);
  AngularRT(const AngularRT& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new AngularRT(*this,newname); }
  inline virtual ~AngularRT() { }

protected:

  RooRealProxy ctK ;
  RooRealProxy ctL ;
  RooRealProxy phi ;
  RooRealProxy FsS ;
  RooRealProxy AsS ;
  RooRealProxy As5S ;
  RooRealProxy FlS ;
  RooRealProxy P1S ;
  RooRealProxy P5pS ;
  
  Double_t evaluate() const ;

private:

  ClassDef(AngularRT,1) // Your description goes here...
};
 
#endif
